TransitTalk/Transit-Talk

- app/assets/javascripts/application.js
Probably commented out by mistake.
Tip: If not, don't comment out stuff, that's what git is for :-)
> Include all Javascript

- CONTRIBUTING.md
Revises some simple markdown errors and updates text for readme and contribution-oriented pages.
> Documentation and Repository Information Updates

- CONTRIBUTING.md
- CONTRIBUTORS.md
I'll be getting on board with this project in full quite soon, but I wanted to jump in with a couple quick revisions to CONTRIBUTING.md and CONTRIBUTORS.md beforehand. The wiki isn't in existence yet, so I can't post a rundown of my proposed changes there, but I hope the information in this PR will suffice.
> Slight copy revisions

- Gemfile
- Gemfile.lock
- README.md
- test/test_helper.rb
This adds the Ruby on Rails implementation of Coveralls based on their documentation, and adds a nice Coveralls badge to our README. The badge will currently say unknown, since `master` does not yet have Coveralls (and has not been run with it).
> Added Coveralls

- app/controllers/favorites_controller.rb
- app/controllers/lines_controller.rb
- app/controllers/pages_controller.rb
- app/models/line.rb
- app/models/stop.rb
- app/models/user.rb
- test/controllers/issues_controller_test.rb
- test/controllers/lines_controller_test.rb
- test/controllers/stops_controller_test.rb
- test/models/issue_test.rb
- test/models/line_test.rb
- test/models/stop_test.rb
- test/rails_helper.rb
- test/test_helper.rb
If these look all right then `rake rubocop` will pass completely.
> Rubocleanup two

- .travis.yml
Adjusting Travis behavior, so I'm putting up a PR to see how CI behaves with this config. My apologies for the noise this generates.
> adds linting before rspec in travis config

- app/assets/stylesheets/application.scss
I've submitted a test PR to see if this is working and if it's what you had in mind.
*
*
- #.
#
> increase font size to address issue #43

- app/views/favorites/index.html.erb
- app/views/lines/index.html.erb
- app/views/pages/history.html.erb
- app/views/pages/view_issues.html.erb
Caravan had a bunch of different ways of showing text that replaced content, so I standardized it to always use an `<em>` tag (italics), and use a standardized CSS class so we can style it all the same way later on.
This also added placeholder text to the lines page, so if you have no lines loaded into your DB locally, it'll tell you.
Manually tested to make sure everything looked good.
-
> Add & Standardize Placeholder Text

- CONTRIBUTING.md
- README.md
change README.md and CONTRIBUTING.md 
Caravan -> Transit Talk
Link was modified only for those that are not likely to be affected
- #120[https://github.com/CaravanTransit/Transit-Talk/issues/120]
> Refact reference transit talk name

- app/views/issues/_form.html.erb
> 116 added options for types in issues form

- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/devise.rb
Reverts TransitTalk/Transit-Talk#129
> Revert "Prod mailer confiq"

- .gitignore
This isn't an issue fix. This is a test (and part of my installation since I'm using a different IDE)
> Remove Rubymine related files from the repo

- app/assets/stylesheets/home.scss
- app/views/pages/home.html.erb
While this commit makes a slight improvement to the separator responsive, the dimensions still aren't perfect seemingly due to parent div styling
-
> tweak separator styling

- Gemfile
- Gemfile.lock
> update mysql gem

- README.md
- Added Windows/WSL specific setup instructions
- Added additional details for `mysql2` gem for Windows and macOS platforms
- Cleaned up Markdown formatting
- Confirmed README looked acceptable on GitHub website
- Closes #156 
- **Did not test**: I assumed changing just README.md wouldn't affect tests
> Closes #156 - Update README with additional setup instructions

- app/assets/stylesheets/home.scss
- app/views/pages/home.html.erb
> fix broken svgs

- app/assets/stylesheets/home.scss
> Add semicolons to make CI happy

- app/controllers/pages_controller.rb
- app/models/stop.rb
- app/views/lines/_tiles.html.erb
- app/views/lines/show.html.erb
- app/views/pages/view_issues.html.erb
- app/views/stops/_show.html.erb
- db/migrate/20191029201117_add_serviced_by_to_stops.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/create_transit.rake
This will allow us to access the type of the stop more easily.
I've added a new way to get the count of issues on a stop that's much more performance-friendly.
Manual testing.
> I've added the 'served_by' string to the stop model.

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/issues_controller.rb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
- app/views/lines/index.html.erb
- app/views/lines/show.html.erb
- app/views/pages/about.html.erb
- app/views/pages/search.html.erb
- app/views/pages/view_issues.html.erb
- test/controllers/issues_controller_test.rb
Remove all lower-corner buttons.
> Remove all login prompts outside of sign-in page.

- app/controllers/pages_controller.rb
- app/views/lines/_show.html.erb
- app/views/pages/home.html.erb
- test/controllers/pages_controller_test.rb
BTW - users can't favorite lines, so I removed that bit of code.
Imagine - a world where your favorite stops are available to you in **fewer clicks**. Open your eyes. That world is now a reality. ✨ 
There are new tests in a new file called homepage controller test.
> Added favorites to the homepage, as well as some tests.

- CONTRIBUTING.md
Separated overall project development and city-specific development, added some additional resources, and generally re-organized contributing guide to be more useful, both on its own and when referenced from the wiki.
Markdown updates only, only in-browser tests needed.
Any feedback on the content of the document is welcome!
> Updated and re-organized contributing guide

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/stops.scss
> padding and sizing improvements

- app/assets/stylesheets/home.scss
- app/controllers/issues_controller.rb
- app/views/issues/_form.html.erb
- app/views/pages/home.html.erb
- app/views/stops/_nearby_table.erb
> Text changes
