app/assets/stylesheets/application.scss
app/views/favorites/index.html.erb
app/views/pages/dashboard.html.erb

I've added text to indicate when viewing a page that would list favorites (in particular, the homepage and the favorites page):
Old vs New Homepage:

Added Text When Users Have No Favorites

---

app/assets/stylesheets/headers.scss
app/assets/stylesheets/lines.scss
app/controllers/stops_controller.rb
app/views/stops/_show.html.erb
app/views/stops/_show_with_issues.html.erb
app/views/stops/show.html.erb
config/routes.rb

I've fixed an issue on the homepage where lines would show up if a stop had no issues, I've setup individual stop pages to display issues on stops, and made all displays of stops link to the individual stop page.
Comparison screenshots of homepage (Old VS New respectively):
An individual stop page:
Also fixed search being missing due to long "Transit Network title". This bug was on `master` but was not deployed to production, which has a different title.

Issue Viewing Improvements

---

app/views/issues/_show_list.html.erb
app/views/stops/_show_with_issues.html.erb
app/views/stops/show.html.erb

This pull request fixes the time displayed on issues consistently being listed as "10 minutes ago" and not using the issue's `created_at` attribute. It also refactors some duplicate code that displays a list of issues, which will probably be used enough that it should be modularized into one place.

Fix Issue Time Being Consistently 10 Minutes Ago

---

.gitignore
Gemfile
Gemfile.lock
README.md
app/assets/stylesheets/lines.scss
app/controllers/lines_controller.rb
app/controllers/pages_controller.rb
app/models/line.rb
app/models/stop.rb
app/views/issues/_form.html.erb
app/views/lines/_show.html.erb
app/views/lines/_tiles.html.erb
app/views/lines/show.html.erb
db/migrate/20170822034621_add_onestop_id_to_lines.rb
db/migrate/20170822035000_add_onestop_id_to_stops.rb
db/migrate/20170822035019_move_lines_stops_to_onestop_ids.rb
db/migrate/20170829123148_add_extra_transit_land_data_to_lines.rb
db/schema.rb
lib/tasks/create_transit.rake

This is a long time coming, and should resolve issue #20. I've added a new rake task to grab data for a transit provider from Transitland, added that info to the README, reconfigured the database to take advantage of Transitland data, and reworked line and stop display to work with transitland data.
I'm marking myself as the assignee for this pull request, as I'll be the one deploying these changes and resetting the database to get new data for the CTA from Transitland.
**Important note:** these changes deprecate importing from a raw GTFS file, as that inherently uses different fields and ways of handling data.

Move to Transitland

---

app/controllers/pages_controller.rb

Changed the hard-coded stop radius to 0.2 miles to prevent stop list crowding in dense areas. Eventually, this hardcoded radius will be replaced by a smarter system, as discussed in issue #54.

Hard-coded stop radius 0.5 mi -> 0.2 mi

---

app/assets/javascripts/application.js
app/controllers/issues_controller.rb
app/models/issue.rb
app/models/line.rb
app/models/stop.rb
app/models/user.rb
app/views/issues/_form.html.erb
db/migrate/20170829151944_rename_stop_id_to_one_stop_id.rb
db/schema.rb
lib/tasks/create_transit.rake

This fixes the Transitland job by making it use an import instead of individual SQL calls, makes `onestop_id` the primary key of stops and lines, and then moves over issues and favorites to use this system. There are a few improvements that could be made, such as the fact that routing still uses `line_id` and `stop_id`, but this has been deployed for the sake of getting a working demo going.

Move to Transitland Fixes

---

app/views/layouts/application.html.erb
config/environments/production.rb

I've changed logging to be more concise and not log partial renders, which should help prevent us hitting Papertrail limits. I've also added Google Analytics to Transit Network, which should help us track if we're getting unusual traffic.

Adjust Logging and Add Analytics

---

README.md
app/views/layouts/application.html.erb
app/views/pages/about.html.erb
config/app.yml
config/application.rb
config/environments/production.rb
config/initializers/session_store.rb

This pull request refactors the code to fix any references to Transit Network, whether it be in written content or links to GitHub. Take a look!

Refactor Code References from Transit Network to Caravan

---

config/database.yml

Renaming the test db allows data pulled in for local development to persist when across test runs.
I was poking around a things, and noticed that I unexpectedly lost my local data. As it turns out the test and development databases were identical, so running Rake wiped the local db. It seems that running tests should not do that. If someone is building out changes to the UI and wants to run tests making them reload data every time to populate the UI after a test run is going to discourage well-tested code.
Caveat: I'm new to this project, so maybe I'm missing something about how we get tests to play nice with development data.

running `rake test` or `rake` will not blow away development db

---

Gemfile
Gemfile.lock
app/channels/application_cable/channel.rb
app/channels/application_cable/connection.rb
app/controllers/application_controller.rb
app/controllers/favorites_controller.rb
app/controllers/issues_controller.rb
app/controllers/lines_controller.rb
app/controllers/pages_controller.rb
app/controllers/stops_controller.rb
app/helpers/application_helper.rb
app/helpers/issues_helper.rb
app/jobs/application_job.rb
app/mailers/application_mailer.rb
app/models/application_record.rb
app/models/issue.rb
app/models/line.rb
app/models/setting.rb
app/models/stop.rb
app/models/user.rb
app/models/vehicle.rb
test/controllers/issues_controller_test.rb
test/controllers/lines_controller_test.rb
test/controllers/stops_controller_test.rb
test/models/issue_test.rb
test/models/line_test.rb
test/models/stop_test.rb
test/models/user_test.rb
test/rails_helper.rb
test/test_helper.rb

Now that we have rubocop in available and configured to an acceptable standard it is a good time to revise files to match that standard. Rubocop's `--auto-correct` flag is a great way to mass update files.
In order to keep this PR's scope reasonable didn't update everything at once, and instead just corrected the top 3 offenders:
```
36   Style/StringLiterals
28   Style/FrozenStringLiteralComment
22   Layout/TrailingWhitespace
```
If these look good this I can tackle what is left in another PR. Here is what would remains after this one:
```
bundle exec rubocop --format offenses --out ~/offenses.txt 'app/**/*.rb' 'lib/**/*.rb' 'test/**/*.rb'
16  Style/HashSyntax
11  Layout/EmptyLinesAroundClassBody
5   Layout/IndentationWidth
5   Layout/TrailingBlankLines
5   Metrics/LineLength
2 …
```

Rubo corrections

---

Gemfile.lock
db/schema.rb

Updated gems to fix security issues pointed out by GitHub. We should test this to make sure everything still works fine.
Here are the gems GitHub pointed out issues with:
None.
N/A

Updated all gems to fix security issues

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
config/app.yml
config/locales/en.yml

This removes the hard-coded "Chicago" reference on the homepage, and instead makes it pull from a city name site setting that defaults to "Our City". When this is deployed, we'll need to update the setting on the live app to "Chicago", but this will prevent any hard-coded CTA specific language.
This also styles global messages to be clearer so that Rails messages from Caravan are intuitive. Here's some screenshots:
| Alert (Negative) | Notice (Positive) |
| --- | --- |
| ![screenshot from 2018-10-16 20-08-11](https://user-images.githubusercontent.com/3187531/47055899-5a401100-d17f-11e8-807b-7862324fbba1.png) | ![screenshot from 2018-10-16 20-07-52](https://user-images.githubusercontent.com/3187531/47055900-5a401100-d17f-11e8-9e28-c1d341fb9178.png) |
Manual testing by signing in to see a …

Add City Name Site Setting & Style Global Messages

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/forms.scss
app/assets/stylesheets/headers.scss
app/assets/stylesheets/lines.scss
app/assets/stylesheets/loginFields.scss
app/assets/stylesheets/variables.scss.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/lines/show.html.erb
app/views/shared/_header.html.erb

This pull request fixes issues with the Devise forms looking bad on desktop, and generally improves them for all devices. It also makes it so that the page content and header are restricted to 1200px on desktop, to make content centered. Forms are centered at 600px width.
Additionally, I updated the styling so form inputs are a little more padded and rounded, "pill" buttons now are not pills (it just didn't fit everything else), and making the simple links WCAG 2.0 AA contrast compliant as well as having a hover effect on all links.
Here are some comparison screenshots, with the before screenshot first.
| Before | After |
| --- | --- |
| ![screenshot from 2018-11-20 20-24-46](https://user-images.githubusercontent.com/3187531/48814958-5e24fd00-ed02-11e8-82c5-ad67286e06a2.png) | …

Improve Desktop Header and General Form Styling

---

README.md
app/views/lines/index.html.erb
app/views/pages/about.html.erb
app/views/pages/home.html.erb
config/app.yml

Changes all references to old "Caravan" project name within the app, with the exception of filenames. Additionally, fixes a slight typo in the new "Transit Talk" name on the README.
Ran app locally to ensure propagation of changes, especially those stemming from the app.yml config file.
- Closes #120

Project name refactor (closes #120)

---

app/models/line.rb
test/models/line_test.rb

This is a first step toward addressing https://github.com/CaravanTransit/Transit-Talk/issues/119. 
This PR adds two new methods to the `Line` model for figuring out whether the line is a bus line or train line.
This distinction seems pretty important and I want to make sure I've got it right.
The code I've written prefers `system_type` to `vehicle_type` when deciding whether a line is a bus line or train line. Also, I've assumed that a train line is either a "tram line" or a "metro line" as defined by GTFS. 
Added several tests to the `Line` model unit test file.
- #119

Add bus? and train? methods to Line model

---

app/controllers/issues_controller.rb
app/models/line.rb
app/views/issues/_form.html.erb
app/views/issues/edit.html.erb
app/views/issues/new.html.erb
app/views/pages/home.html.erb
test/models/line_test.rb

This builds on #124 to restrict the lines you see in the new issue form to the appropriate types of line (depending on whether you clicked the bus or train button).
Added a few tests to the Line model.
- Closes #119

Closes #119. Surface bus/train distinction for issue form

---

Gemfile
Gemfile.lock
app/models/issue.rb
app/models/line.rb
app/models/setting.rb
app/models/stop.rb
app/models/user.rb
app/models/vehicle.rb
lib/tasks/annotate.rake

This PR adds a Rake task and some auto-generated comments to the model files.
The [annotate gem](https://github.com/ctran/annotate_models) is a handy tool I've used in the past that automatically annotates your model files with the schema of the backing table for the model.
IMO, this is really handy. Figure it could help, since it seems like people keep forgetting what's in the DB.

Add schema annotations to models

---

app/models/user.rb
db/migrate/20190410182147_add_ban_flag_to_user.rb
db/schema.rb
lib/tasks/ban.rake
test/models/user_test.rb

This adds a new database field to the user table that records whether or not a user has been banned. For now, a user can easily be banned using a new Rake task that takes an email address and bans the corresponding user.
There are tests for the ban method on the User class.
Still to come: Rejecting login attempts for banned users.
- [ x] Code follows code style of this project
- [x ] Tests added to cover changes
- [x ] All new and existing tests passing

Add migration and rake task for banning users

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/headers.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/normalize.css
app/assets/stylesheets/variables.scss.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

* Added Normalize.css. See info about it [HERE](https://necolas.github.io/normalize.css/).
* Stopped using sprockets require. As noted in the [docs](https://github.com/rails/sass-rails#important-note), it's highly discouraged.
* Removed a good amount of HTML and CSS from the site. Made it much lighter.
Tested in both Firefox and Chrome. Emulated different mobile device screen sizes.
- Right now, the divider SVGs do not expand/shrink horizontally with the page. This is possiblew, but I have no experience with SVGs. [Here's someone doing something similar](https://stackoverflow.com/a/49412909). I don't know enough about SVGs to make this change.

#130 - Implement MVP UI - Homepage

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/variables.scss.erb
app/controllers/application_controller.rb
app/controllers/issues_controller.rb
app/helpers/sessions_helper.rb
app/models/issue.rb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
config/routes.rb
db/seeds.rb

1. I added an "opt out link" on the login page that only shows up when the "from" query parameters.
2. Added JS code to add a "opted out of login" cookie to the user's browser. This cookie is sent to the back-end with every request. Opt out button also goes to the previous page. See the `inferred_last_page_path` method.
3. Added the query parameters to the login for as hidden params. This way, when the user logs in, they will also go to the page that they were trying to access. This is a little bonus. Devise, the library we use for login, allows us to override some methods on our `ApplicationController` (from which all other controllers inherit). [More info here](https://www.rubydoc.info/github/plataformatec/devise/Devise%2FControllers%2FHelpers:after_sign_in_path_for)
Didn't write new …

#134 - remove login barrier

---

README.md

No specific issue, this just updates the README with a little additional info for new contributors who may have issues installing the `mysql2` gem.

NO ISSUE: update README with additional mysql2 gem info

---

.gitignore
.rubocop.yml
.stylelintrc
.travis.yml
Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/dashboard.scss
app/assets/stylesheets/forms.scss
app/assets/stylesheets/headers.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/lines.scss
app/assets/stylesheets/loginFields.scss
app/controllers/issues_controller.rb
ci.sh
package-lock.json
package.json

Fixes CI so it passes on `master`, making it more useful for checking new work.
I also migrated Rubocop per an install warning, adding the `rubocop-rails` gem and a small config change.
Just ran CI!
- None
Also re-enabled Coveralls, which should help by showing code coverage changes on PRs!

Fixed CI Due to Rubocop Failure

---

app/assets/stylesheets/headers.scss

Per Tomer's request, this switches the search icon from the white-colored one to the black-colored one.

switch to black search icon

---

app/controllers/lines_controller.rb
test/controllers/issues_controller_test.rb
test/fixtures/stops.yml

Used  the developer tools in the browser to notice that the values in the stop dropdown don't match those in the database. Looks like plucking the `:id` was bringing out the wrong number. Not sure why. Looks like the `:onestop_id` has the same value and works.
Ran through this in the browser.

Closes #154 - fix association between lines and issues

---

config/environments/production.rb
config/initializers/devise.rb

TBH I don't think this ever worked. Followed instructions of a tutorial online for setting up sendgrid in heroku and found this missing configuration.
**I could not test this locally, so I deployed the branch to heroku and tested it manually there with my personal email.** I can confirm that this works, but only @AcademyInPeril and @vkoves can actually see it in action.

 #108 - fix email sending in production

---

app/controllers/pages_controller.rb

Closes #166 - View Issues throws SQLException
Add check on environment flag. If it is prod, we do the existing geolocation. If it is not, we simply grab the top 50 stops so we don't lose functionality.
Manual testing, rails test.
Closes #166

Add switch for dev/prod stop list generation

---

Gemfile

In the Gemfile there is a line to define the version of ruby that is being used. That information is also defined in the .ruby-version file in the root of the application directory. This change 
Manual testing of doing bundle install, then renaming .ruby-version to .ruby-version.old, rerunning bundle install, then renaming .ruby-version back to its original name and running bundle install one last to time to make sure it works

Read ruby version from .ruby-version in Gemfile to reduce duplication

---

app/controllers/lines_controller.rb
app/controllers/pages_controller.rb
app/controllers/stops_controller.rb
app/models/stop.rb
app/views/stops/_show.html.erb

Long story short - this makes less calls to the DB. Read section 13 in [this link](https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations) to find out why.
Also, `count` makes a DB call but `length` doesn't. Go figure!
- I'm going to create a new PR for not loading the "settings" so often(every page load makes a call to the DB to get the name of the site, which doesn't change very often). However, we'll need to update the version of Ruby that we're using to the latest gems.

Minimize DB calls 

---

app/controllers/pages_controller.rb

Limits search results to 25 of each type. Without this guard, the user can search for an empty string which will match every record in the DB and crash the app.

Add limit of 25 to each result type

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/headers.scss
app/assets/stylesheets/home.scss
app/views/pages/home.html.erb
app/views/shared/_separator.html.erb
app/views/stops/_show.html.erb

Fixing up a few issues we noticed during the demo and over time.
- Converted separators to a purely html/css solution. It now scales much better with different screen sizes.
- Hamburger menu now properly expands from the right side
- "Serviced By" text now gets left-aligned in the div, fixing weird-looking text when enough transfer circles exist to make it go into two lines

Style touchups
